### ISSUE TITLE
Add options to convert hyphen-case to camelCase?

### ISSUE THREAD

**Issue by pxwee5** [pmowrer/node-sass-json-importer#77]
Can we add an option to convert hyphen-case to camelCase and vice versa ?

Because of this: https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-CSS2Properties

In CSS it's more natural to call hyphen-case (E.g. `color: $sky-blue`)
But in Javascript it's more natural to call camelCase (E.g. `this.color = variable.skyBlue`, probably too ugly to call `variable['sky-blue']` even though it's ok to do so)

**Comment by anthonylebrun** [comment]
Will have a PR shortly.

**Comment by anthonylebrun** [comment]
Cool, opened a PR that includes feature + tests + docs. Lemme know if there's anything I can change!

The structure of src/index.js is feeling a bit strange now that I'm passing the options around like that. Perhaps it's time to consider using either a class or constructor function to store settings as state?

**Comment by pmowrer** [comment]
Thanks @anthonylebrun, nice work! 👍 

> The structure of src/index.js is feeling a bit strange now that I'm passing the options around like that. Perhaps it's time to consider using either a class or constructor function to store settings as state? 

Agree, but not too worried about it yet. Feel free to submit a refactor if you feel up to it.

**Comment by anthonylebrun** [comment]
🥳 

Ok, I may if the fancy strikes me!
