### ISSUE TITLE
Allow to import *.js files. Files exporting an JS object.

### ISSUE THREAD

**Issue by alfredriesen** [pmowrer/node-sass-json-importer#84]
I have a need to import various json files. It is a migration from stylus, where I was able to import those json files and assign each to a variable. I do not have this option with this importer.

It would be helpful to be able to import Files exporting an JS object. Example:
```
const xl = require('./variables.json')
const md = require('./variables-md.json')
const xs = require('./variables-xs.json')
const bscolor = require('./colors.json')

module.exports = {
    xl,
    md,
    xs,
    bscolor,
}
```

I have tested it with just one modification on this line in your source and it works:
`return /\.js(on5?)?$/.test(url);`
https://github.com/pmowrer/node-sass-json-importer/blob/master/src/index.js#L47

**Comment by pmowrer** [comment]
I'd be happy to merge if you made a PR for it (please also add something about the new feature to the README). Please make sure the commit message begins with `feat:` in order to trigger an automatic release on merge.

**Comment by pmowrer** [comment]
Closed by https://github.com/pmowrer/node-sass-json-importer/pull/90. Thanks @alfredriesen!
