### ISSUE TITLE
importer.call is not a function

### ISSUE THREAD

**Issue by soelen** [pmowrer/node-sass-json-importer#85]
Somehow using the cli importer seems not to work anymore
`./node_modules/.bin/node-sass --importer node_modules/node-sass-json-importer/dist/cli.js --recursive ./src --output ./dist`

```
"node-sass": "^4.11.0",
"node-sass-json-importer": "^4.1.2",
```
```
node_modules/node-sass/lib/index.js:338
        var result = importer.call(options.context, file, prev, done);
                              ^

TypeError: importer.call is not a function
    at options.importer (node_modules/node-sass/lib/index.js:338:31)
```

**Comment by fbrosda** [comment]
Hi,

I just discovered the same problem and I think this is somehow related to the conversion of the es6 modules to common-js modules.

In node-sass the `importer` is actually an object and the correct function is buried in `importer.default`, so using `importer.default.call` produces the expected output.

I can have a look at this and and open a pull request, if I find a solution.
